version: '3.8'

services:
  grafana:
    image: grafana/grafana:10.1.1
    user: root
    restart: always
    # environment:
      # GF_INSTALL_PLUGINS: 'grafana-clock-panel,grafana-simple-json-datasource'
    volumes:
      - ./grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/config.monitoring
    ports:
      - 48040:3000
