version: '3.7'

services:
  mediators_tool:
    image: emlite-mediator-base
    network_mode: host
    environment:
      SUPABASE_URL: http://0.0.0.0:54321
      SUPABASE_KEY: <insert key>
      MEDIATOR_IMAGE: emlite-mediator-base
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
