name: Build and Push Docker Images

on:
  push:
    tags:
      - "*"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: cepro/emlite-mediator

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Git Tag
        id: extract_tag
        run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      
      - uses: superfly/flyctl-actions/setup-flyctl@1.5
        with:
          version: 0.2.55
      - name: Auth Pushes to Fly.io docker registry
        run: "flyctl auth docker"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Build and push server Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile
          push: true
          tags: |
            ghcr.io/cepro/emlite-mediator:${{ steps.extract_tag.outputs.tag }}
            registry.fly.io/emlite-mediator:${{ steps.extract_tag.outputs.tag }}
